### ISSUE TITLE
Moving documnetation to https://readthedocs.org/ ?

### ISSUE THREAD

**Issue by varenius** [jive-vlbi/jive5ab#15]
Now, firstly let me say that the jive5ab PDF documentation is great! Clear, extensive, and very helpful. It is really great!

However, as I have browsed various revisions during the years, I wonder if it perhaps would be worth moving the documentation to a helpful service like https://readthedocs.org/ ? Many other things live there, it could perhaps be an idea.

**Comment by haavee** [comment]
In fact, this has been undertaken by @shaoguangleo in this (already accepted) PR https://github.com/jive-vlbi/jive5ab/pull/35
