### ISSUE TITLE
Curious unprovoked one-time error "udpsnorreader_stream: not allowed to push variable block of size 0 bytes for stream 8 (lost)"

### ISSUE THREAD

**Issue by varenius** [jive-vlbi/jive5ab#21]
Please consider this output from recent datastreams split-by-VDIF-thread-id recording this morning. All scans in 12 h obs time worked find, then this one:
```
202208406:14:01 2022-03-25 05:14:01.23: Processing command 'disk2file?'
202208406:14:01 2022-03-25 05:14:01.23: Reply: !disk2file? 0 : inactive : /data/check_data//checkdata.vdif ;
202208406:14:26 2022-03-25 05:14:26.99: Processing command 'record=on:vo2083_oe_084-0514a'
202208406:14:26 2022-03-25 05:14:27.00: getsok: req. server socket@udpsnor:26311
202208406:14:26 2022-03-25 05:14:27.00: Reply: !record=  0  ;
202208406:14:26 2022-03-25 05:14:27.00: udpsnorreader_stream: fd=9 data:8032 total:8040 pkts:31872 avbs: 1
202208406:14:26 2022-03-25 05:14:27.00: per_sender_type[10.100.0.107:46227] - first sequencenr# 4812800702
202208406:14:26 2022-03-25 05:14:27.00: handle_seqnr[10.100.0.107:46227] - switch to ACK every 10th packet
202208406:14:26 2022-03-25 05:14:27.00: per_sender_type[10.100.0.102:46227] - first sequencenr# 4814400718
202208406:14:26 2022-03-25 05:14:27.00: handle_seqnr[10.100.0.102:46227] - switch to ACK every 10th packet
202208406:14:26 2022-03-25 05:14:27.00: per_sender_type[10.100.0.103:46227] - first sequencenr# 4814080699
202208406:14:26 2022-03-25 05:14:27.00: handle_seqnr[10.100.0.103:46227] - switch to ACK every 10th packet
202208406:14:26 2022-03-25 05:14:27.00: per_sender_type[10.100.0.106:46227] - first sequencenr# 4813120722
202208406:14:26 2022-03-25 05:14:27.00: handle_seqnr[10.100.0.106:46227] - switch to ACK every 10th packet
202208406:14:26 2022-03-25 05:14:27.00: Processing command 'record?'
202208406:14:26 2022-03-25 05:14:27.00: Reply: !record?  0 : on : 5309 : vo2083_oe_084-0514a : 683400 ;
202208406:14:26 2022-03-25 05:14:27.00: per_sender_type[10.100.0.101:46227] - first sequencenr# 4814720703
202208406:14:26 2022-03-25 05:14:27.00: handle_seqnr[10.100.0.101:46227] - switch to ACK every 10th packet
202208406:14:26 2022-03-25 05:14:27.00: per_sender_type[10.100.0.105:46227] - first sequencenr# 4813440707
202208406:14:26 2022-03-25 05:14:27.00: handle_seqnr[10.100.0.105:46227] - switch to ACK every 10th packet
202208406:14:26 2022-03-25 05:14:27.00: per_sender_type[10.100.0.100:46227] - first sequencenr# 4815040711
202208406:14:26 2022-03-25 05:14:27.00: handle_seqnr[10.100.0.100:46227] - switch to ACK every 10th packet
202208406:14:26 2022-03-25 05:14:27.00: per_sender_type[10.100.0.104:46227] - first sequencenr# 4813760712
202208406:14:26 2022-03-25 05:14:27.00: handle_seqnr[10.100.0.104:46227] - switch to ACK every 10th packet
202208406:14:29 2022-03-25 05:14:29.01: Processing command 'record?'
202208406:14:29 2022-03-25 05:14:29.01: Reply: !record?  0 : on : 5309 : vo2083_oe_084-0514a : 2050577880 ;
202208406:14:29 2022-03-25 05:14:29.01: Processing command 'evlbi?'
202208406:14:29 2022-03-25 05:14:29.01: Reply: !evlbi? 0 : total : 255047 : loss : 0 ( 0.00%) : out-of-order : 0 ( 0.00%) : extent : 0seqnr/pkt ;
202208406:14:54 2022-03-25 05:14:54.70: udpsnorreader_stream: not allowed to push variable block of size 0 bytes for stream 8 (lost)
202208406:14:54 OH NOES! A step threw an exception:
202208406:14:54 **** ::recvmsg(network->fd, &msg, /*flags*/) fails - [] (ask:24 or 8040 got:408)
202208406:14:54 2022-03-25 05:14:54.99: net2vbs guard function: transfer done
202208406:14:56 2022-03-25 05:14:56.99: Processing command 'record=off:vo2083_oe_084-0514a'
202208406:14:56 2022-03-25 05:14:56.99: Reply: !record=  6 : Not doing record ;
202208406:14:57 2022-03-25 05:14:57.34: Processing command 'status?'
202208406:14:57 2022-03-25 05:14:57.34: Reply: !status?  0 : 0x00000003 : -1 : [chain::run_step/step threw exception] ::recvmsg(network->fd, &msg, /*flags*/) fails - [] (ask:24 or 8040 got:408) : 2022y084d05h14m54.7187s ;
202208406:14:57 2022-03-25 05:14:57.34: Processing command 'error?'
202208406:14:57 2022-03-25 05:14:57.34: Reply: !error? 0 : -1 : [chain::run_step/step threw exception] ::recvmsg(network->fd, &msg, /*flags*/) fails - [] (ask:24 or 8040 got:408) : 2022y084d05h14m54.7187s :  :  ;
202208406:14:57 2022-03-25 05:14:57.34: Processing command 'status?'
202208406:14:57 2022-03-25 05:14:57.34: Reply: !status?  0 : 0x00000001 ;
```
It seems to me that the error is unprovoked, i.e. no input command immediately preceeding it. There are no other issues before or after. I wonder, when could this error, i.e. `udpsnorreader_stream: not allowed to push variable block of size 0 bytes for stream 8 (lost)`  happen? Should we write this off as a temporary CPU harddrive (neutrino) interaction?

**Comment by haavee** [comment]
Hi Eskil, I see two things.
First: the root cause is this

    202208406:14:54 OH NOES! A step threw an exception:
    202208406:14:54 **** ::recvmsg(network->fd, &msg, /*flags*/) fails - [] (ask:24 or 8040 got:408)

You probably got port-scanned, just like we were during the e-VLBI just before the end. This makes the recording process stop. The thing you worry about:

    202208406:14:54 2022-03-25 05:14:54.70: udpsnorreader_stream: not allowed to push variable block of size 0 bytes for stream 8 (lost)
    
is due to a lack of proper boolean understanding of the author - an erroneous `if () { ... } else { ... }` where the `else` clause should not have executed in _this_ case. You should not have seen this message. Check `threadfns.cc:2663`.
Will fix this, thanks for reporting!

**Comment by varenius** [comment]
Interesting. Would the port-scan be an issue because of the open jive5ab com-port, or because of the open jive5ab data-port?

**Comment by haavee** [comment]
Hi E; must be dataport - because of several pointers of info:
- root cause error mentions  `ask: xxx or yyy got: zzz`: command port never has any expectation on how much to read

- command port listens on tcp; port scan on tcp either do connect() - and then would see error from main loop about unknown command (if any data sent), or tcp syn check but that would not end up at application level

- recording stops, which is only because data file descriptor closed, which only happens b/c unexpected amount of data seen; mishaps on command socket would never interrupt recording

**Comment by varenius** [comment]
Thanks. After some local testing, I confirm the problem can be reproduced with a port scan, and fixed by filtering any incoming non-observatory traffic on the jive5ab UDP data ports. To trigger the error (without any filters in place) I start a jvie5ab recording, and then I fire this command at the recorder (TESTPORT and IP have been masked): 
```
sudo nmap -p TESTPORT -sU IP
...
PORT      STATE         SERVICE
TESTPORT/udp open|filtered unknown
...
```
this instantly triggers jive5ab to fail, with the log message
```
202208421:52:09 OH NOES! A step threw an exception:
202208421:52:09 **** ::recvmsg(network->fd, &msg, /*flags*/) fails - [] (ask:24 or 8040 got:0)
```
We then apply firewall rules as
```
sudo iptables -I INPUT -p udp -m multiport --dports PORT -s ALLOWED_IP -j ACCEPT
sudo iptables -A INPUT -p udp -m multiport --dports PORT -j DROP
```
where ALLOWED_IP is something like 1.2.3.4/24 describing the subnet of allowed IP adresses. 

After this change, jive5ab will record just fine without any issues even if I bombard it with nmap requests! Problem solved!

Side note: I still get the same reply from nmap as `TESTPORT/udp open|filtered unknown`. I would have assumed the port to say "closed" or something like that, but that's just my nmap ignorance I guess.
