### ISSUE TITLE
multithread scancheck

### ISSUE THREAD

**Issue by BeppeMc** [jive-vlbi/jive5ab#22]
After a multi-thread recording, scan_check desn't return info for each datastream. Jive5ab complains with:
scan_check?
> !scan_check ? 4 : /root/jive5ab/src/libvbs.cc@842 assertion [(rv.insert(filechunk_type(dir+"/"+*p))).second]
> fails  duplicate insert for chunk __testa_ds3S.00000000;

**Comment by haavee** [comment]
Hi Beppe,
I think I only now fixed the issues; see two commits of today (9 Dec) in this branch https://github.com/jive-vlbi/jive5ab/commits/issue-22
That one (finally) scan_checks both individual data stream recordings and the combined recording OK
