### ISSUE TITLE
disk2file empty result w/ multi file recording

### ISSUE THREAD

**Issue by haavee** [jive-vlbi/jive5ab#25]
The reason is that `scan_set=:<time>:<time>` was not updated to use the new `scan_check?` algorithm; if `scan_set=` detects usage of `time` in the parameters it does an (implicit) mini-scan check to be able to compute byte offsets for any following `disk2*`. Probably that fails on the multi-file recordings, setting the file pointers erroneous.

In the log sent by Ys I noticed this:

    2023-02-17 16:07:20.56: vbsreader_c: start reading fd#2147483647, 22206870218528 => 510666528
    2023-02-17 16:07:20.56: vbsreader_c: done 0byte

which means the `start` byte was >> `end` byte (in fact, a lot larger than the file itself)

**Comment by psi-c** [comment]
Issue25 doesn't like building on at least gcc-9 to gcc-11.

` 72%] Building CXX object src/CMakeFiles/jive5ab.dir/mk5command/scan_set_vbs.cc.o
In file included from /usr/local/src/jive5ab-issue25-cf592eb/src/xlrdevice.h:87,
                 from /usr/local/src/jive5ab-issue25-cf592eb/src/runtime.h:26,
                 from /usr/local/src/jive5ab-issue25-cf592eb/src/mk5command/mk5.h:26,
                 from /usr/local/src/jive5ab-issue25-cf592eb/src/mk5command/scan_set_vbs.cc:20:
/usr/local/src/jive5ab-issue25-cf592eb/src/countedpointer.h: In constructor ‘countedpointer<T>::cPtrBlock::cPtrBlock(unsigned int) [with T = data_reader_type]’:
/usr/local/src/jive5ab-issue25-cf592eb/src/countedpointer.h:310:11: error: ‘*this.countedpointer<data_reader_type>::cPtrBlock::refcnt’ is used uninitialized [-Werror=uninitialized]
  310 |         ++refcnt;
      |           ^~~~~~
cc1plus: all warnings being treated as errors`

Compiler seems not so happy with the idea at
https://github.com/jive-vlbi/jive5ab/blob/70e827ab397f95cdc323a336610a29208ac21fe5/src/countedpointer.h#L255

**Comment by haavee** [comment]
Sir may find, upon `git pull`ing the latest commits on issue-25 branch that
- c++11 support can now be enabled explicitly through `cmake ... -DC++11=ON ...` (which fixes the counted pointer uninitialised memory warning)
- expect other warnings, caused by stricter `g++-11` compilert, to be fixed as well

**Comment by psi-c** [comment]
Happily builds now with either of "-DETRANSFER_ROOT=...." or "-DC++11=ON " on g++8 to 11!
