### ISSUE TITLE
Datastream and trouble with scan name

### ISSUE THREAD

**Issue by MrBasler** [jive-vlbi/jive5ab#5]
By enabling datastream, jive5ab will save a recording with the name <scan>[a..z]_<suffix>.  If <scan>[a..z] already exist, such as may be the case for a test recording, it will not properly detect the <scan>[a..z]_<suffix> because it is looking for <scan>[a..z]. This will overwrite the last <scan>[a..z]_<suffix>. vbs_ls will then output that you may have a duplicate file.
If vbs_ls output
   test_station_test
   test_station_testa
   test_station_testb_0
   test_station_testb_1
If you then do a scan with name test, you will get the following
   test_station_test
   test_station_testa
   test_station_testb_0     duplicate
   test_station_testb_1     duplicate

**Comment by haavee** [comment]
Can you check out the issue-5 branch and play around with that?
It should now generate files "test_station_test_ds=0" and "test_station_test_ds=1" etc. - to be more compliant to standardized (e-)VLBI file naming conventions.

Basically a data stream label now gets appended as "_ds=<label>" in stead of just "_<label>"

**Comment by haavee** [comment]
This issue has been addressed and should be solved in jive5ab-3.1.0 release or later (not yet in 3.2.0-dev, which is the master branch at the moment)
