### ISSUE TITLE
tstat? reports Gbps, Mbps - but it is Gibps, Mibps

### ISSUE THREAD

**Issue by varenius** [jive-vlbi/jive5ab#7]
As per https://github.com/jive-vlbi/jive5ab/issues/6#issuecomment-707179711 it seems "tstat?" reports data rate in Gbps and Mbps but it is actually Gibps and Mibps. One could argue either the reported unit should change, or the value reported should change, so the values match the units?

**Comment by haavee** [comment]
Please check https://github.com/jive-vlbi/jive5ab/tree/issue-7 whether that is more to your expectation/liking.
The units now are `[afnumkMGTExa]ibs` to indicate base-1000 bits per second.

**Comment by kettenis** [comment]
The confusion between base-1000 and base-1024 for only really exists for "memory" (including non-volatile memory such as disks). Network transfer speeds have always been proper (i.e. base-1000) bits, so they should be reported as Gbps (1000000000 bps) or Mbps (1000000 bps).  Gibps and Mibps should not be used in my opinion.

Of course the VLBI community has turned this into a dog's breakfast where "megabit per second" means 1000000 bits per second, but "gigabit per second" means 1024 * 1000000 bits per second. You can always rely on astronomers messing up their units!

**Comment by haavee** [comment]
I intend to close this issue despite not handling the "ibps"/"bps" as best as possible. At least there is *a* unit with the value that correponds with what the value represents which is still an improvement I hope. Can always be reopened and a better fix requested if deemed important enough.
